export const FLAVORS = [
  {
    id: 'mango',
    name: 'Mango',
    tagline: 'King of Fruits, Royal Delight',
    description: 'Sun-ripened Alphonso mangoes blended into a velvet smooth nectar that bursts with rich sweetness and tropical warmth.',
    bottleImg: '/products/mango_bottle.png',
    solidBg: '#4A90E2',
    primaryColor: '#0D5C9F',
    accentColor: '#FF9F00',
    secondaryColor: '#39B54A',
    bgColor: '#FFFFFF',
    gradientBg: 'linear-gradient(135deg, #FFFFFF 0%, #F8FCFF 60%, #EEF6FF 100%)',
    glowColor: 'rgba(255, 255, 255, 0.25)',
    textColor: '#1E293B',
    fruitElements: ['🥭', '✨', '🍃'],
    nutrition: { calories: '120 kcal', fruitContent: 'Premium Nectar', vitaminC: '90% RDI', sugar: 'Fruit Sugar' },
    badge: 'Best Seller'
  },
  {
    id: 'lychee',
    name: 'Lychee',
    tagline: 'Exotic Floral Sweetness',
    description: 'Handpicked juicy lychees offering a delicate, aromatic burst of refreshment that melts luxuriously on your palate.',
    bottleImg: '/products/lychee_bottle.png',
    solidBg: '#FF5E89',
    primaryColor: '#0D5C9F',
    accentColor: '#FF4D8D',
    secondaryColor: '#39B54A',
    bgColor: '#FFFFFF',
    gradientBg: 'linear-gradient(135deg, #FFFFFF 0%, #F8FCFF 60%, #EEF6FF 100%)',
    glowColor: 'rgba(255, 255, 255, 0.25)',
    textColor: '#1E293B',
    fruitElements: ['🌸', '✨', '🍃'],
    nutrition: { calories: '105 kcal', fruitContent: 'Premium Nectar', vitaminC: '85% RDI', sugar: 'Fruit Sugar' },
    badge: 'Trending'
  },
  {
    id: 'orange',
    name: 'Orange Drink',
    tagline: 'Sunshine Citrus Blast',
    description: 'Crisp Valencia oranges cold-pressed for maximum Vitamin C vibrancy and a perfectly balanced tangy-sweet punch.',
    bottleImg: '/products/orange_bottle.png',
    solidBg: '#FF8A00',
    primaryColor: '#0D5C9F',
    accentColor: '#FF7A00',
    secondaryColor: '#39B54A',
    bgColor: '#FFFFFF',
    gradientBg: 'linear-gradient(135deg, #FFFFFF 0%, #F8FCFF 60%, #EEF6FF 100%)',
    glowColor: 'rgba(255, 255, 255, 0.25)',
    textColor: '#1E293B',
    fruitElements: ['🍊', '✨', '🍃'],
    nutrition: { calories: '110 kcal', fruitContent: 'Premium Nectar', vitaminC: '100% RDI', sugar: 'Fruit Sugar' },
    badge: 'Vitamin C Rich'
  },
  {
    id: 'pineapple',
    name: 'Pineapple',
    tagline: 'Golden Island Refreshment',
    description: 'Sweet, golden Hawaiian pineapples crafted into a vibrant, thirst-quenching elixir infused with tropical sunshine.',
    bottleImg: '/products/pineapple_bottle.png',
    solidBg: '#F5B000',
    primaryColor: '#0D5C9F',
    accentColor: '#FFC700',
    secondaryColor: '#39B54A',
    bgColor: '#FFFFFF',
    gradientBg: 'linear-gradient(135deg, #FFFFFF 0%, #F8FCFF 60%, #EEF6FF 100%)',
    glowColor: 'rgba(255, 255, 255, 0.25)',
    textColor: '#1E293B',
    fruitElements: ['🍍', '✨', '🍃'],
    nutrition: { calories: '115 kcal', fruitContent: 'Premium Nectar', vitaminC: '95% RDI', sugar: 'Fruit Sugar' },
    badge: 'Exotic'
  },
  {
    id: 'guava',
    name: 'Pink Guava',
    tagline: 'Velvety Tropical Indulgence',
    description: 'Aromatic pink guavas blended into a silky, fiber-rich nectar with an unforgettable fruity fragrance.',
    bottleImg: '/products/pink_guava_bottle.png',
    solidBg: '#E95270',
    primaryColor: '#0D5C9F',
    accentColor: '#FF6B8B',
    secondaryColor: '#39B54A',
    bgColor: '#FFFFFF',
    gradientBg: 'linear-gradient(135deg, #FFFFFF 0%, #F8FCFF 60%, #EEF6FF 100%)',
    glowColor: 'rgba(255, 255, 255, 0.25)',
    textColor: '#1E293B',
    fruitElements: ['🍈', '✨', '🍃'],
    nutrition: { calories: '100 kcal', fruitContent: 'Premium Nectar', vitaminC: '120% RDI', sugar: 'Fruit Sugar' },
    badge: 'Fiber Boost'
  },
  {
    id: 'pomegranate',
    name: 'Pomegranate Drink',
    tagline: 'Antioxidant Ruby Nectar',
    description: 'Deep crimson ruby pomegranates brimming with polyphenol antioxidants and a sophisticated tart-sweet profile.',
    bottleImg: '/products/pomegranate_bottle.png',
    solidBg: '#A61B34',
    primaryColor: '#0D5C9F',
    accentColor: '#D32F2F',
    secondaryColor: '#39B54A',
    bgColor: '#FFFFFF',
    gradientBg: 'linear-gradient(135deg, #FFFFFF 0%, #F8FCFF 60%, #EEF6FF 100%)',
    glowColor: 'rgba(255, 255, 255, 0.25)',
    textColor: '#1E293B',
    fruitElements: ['🍎', '✨', '🍃'],
    nutrition: { calories: '125 kcal', fruitContent: 'Premium Nectar', vitaminC: '75% RDI', sugar: 'Fruit Sugar' },
    badge: 'Superfruit'
  },
  {
    id: 'muskmelon',
    name: 'Musk Melon',
    tagline: 'Hydrating Summer Breeze',
    description: 'Subtly sweet, ultra-hydrating melon sips that instantly cool and soothe your senses on warm sunny days.',
    bottleImg: '/products/muskmelon_bottle.png',
    solidBg: '#59B850',
    primaryColor: '#0D5C9F',
    accentColor: '#4CAF50',
    secondaryColor: '#FF9F00',
    bgColor: '#FFFFFF',
    gradientBg: 'linear-gradient(135deg, #FFFFFF 0%, #F8FCFF 60%, #EEF6FF 100%)',
    glowColor: 'rgba(255, 255, 255, 0.25)',
    textColor: '#1E293B',
    fruitElements: ['🍈', '✨', '🍃'],
    nutrition: { calories: '95 kcal', fruitContent: 'Premium Nectar', vitaminC: '80% RDI', sugar: 'Fruit Sugar' },
    badge: 'Hydration Power'
  },
  {
    id: 'nimbu',
    name: 'Nimbu Paani Drink',
    tagline: 'Traditional Indian Zest',
    description: 'Authentic Indian lemon chiller infused with black salt, cumin, and mint for ultimate digestive vitality.',
    bottleImg: '/products/nimbu_pani_bottle.png',
    solidBg: '#C7B900',
    primaryColor: '#0D5C9F',
    accentColor: '#D4E157',
    secondaryColor: '#39B54A',
    bgColor: '#FFFFFF',
    gradientBg: 'linear-gradient(135deg, #FFFFFF 0%, #F8FCFF 60%, #EEF6FF 100%)',
    glowColor: 'rgba(255, 255, 255, 0.25)',
    textColor: '#1E293B',
    fruitElements: ['🍋', '✨', '🍃'],
    nutrition: { calories: '80 kcal', fruitContent: 'Premium Nectar', vitaminC: '110% RDI', sugar: 'Low Sugar' },
  }
];

export const BRAND_INFO = {
  name: 'MEO MIX®',
  company: 'Empire Foods & Beverages',
  tagline: 'Refresh Every Sip',
  description: 'Crafting world-class fruit beverages with premium fruit pulp and ultra-hygienic aseptic bottling technology.',
  phone: '+91 90990 00776',
  email: 'sales.empireindia@gmail.com',
  supportEmail: 'sales.empireindia@gmail.com',
  address: 'Empire Foods & Beverages, Maruti Nandan Ind, Plot No. 2, Lothada, Rajkot - 360022',
  workingHours: 'Mon - Sat: 9:00 AM - 6:00 PM',
  openingHours: '9:00 AM - 6:00 PM',
  socials: {
    instagram: 'https://www.instagram.com/meomixfruitjuice',
    facebook: 'https://www.facebook.com/people/Meo-Mix/100091118232711/?mibextid=LQQJ4d',
    whatsapp: 'https://api.whatsapp.com/send/?phone=919099000776&text&type=phone_number&app_absent=0'
  }
};
